
image: debian

stages:
  - .prenotify
  - test
  - .postnotify


notify-github-pending:
  stage: .prenotify
  when: always
  script:
    - .ci/notify_github.sh pending


# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt-get update -q -y
    - apt-get install -y lua5.4
  script:
    - tests/check-site-conf.sh


notify-github-success:
  stage: .postnotify
  when: on_success
  script:
    - .ci/notify_github.sh success

notify-github-failure:
  stage: .postnotify
  when: on_failure
  script:
    - .ci/notify_github.sh failure